/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hexagonal;

public class App {
}
    public static void main(String[] args) {
        // Crear el adaptador de base de datos
        UserService databaseUserService = new DatabaseUserAdapter();

        // Crear el adaptador de interfaz de usuario y conectarlo con el adaptador de base de datos
        UserInterfaceAdapter userInterfaceAdapter = new UserInterfaceAdapter(databaseUserService);

        // Ahora, puedes interactuar con la aplicación a través del adaptador de interfaz de usuario
        userInterfaceAdapter.createUserFromUI("john_doe", "secretpassword");
        userInterfaceAdapter.displayUserInfo(1);
    }
}
